<br style="clear:both;padding-top:30px;" />
<!-- SLAC Global Footer -->
<div style="text-align:left;padding-left:7px;padding-top:0px;padding-bottom:10px;"><a href="http://www.stanford.edu" target="_blank"><img src="images/stanford-logo-leftnav.gif"></a></div>

<script type="text/javascript">
<!--
    slac_search_and_links = "no";
    search_default = "people";
    custom_search = "no";
    custom_search_type = "";
    custom_search_label = "";
    slac_footer = "yes";
//-->
</script>
<script type="text/javascript" src="http://www-project.slac.stanford.edu/centralNav/slac_global_090212.js"></script>


<div class="footer">
    <a href="http://www6.slac.stanford.edu/Privacy.aspx">Privacy Statement</a>    
</div>
