<!-- Start Left Navigation Menu -->
<ul id="qm1" class="qmmc">
	<li><a href="profile.shtml">SUNCAT Home</a></li>
	<li><a href="reports.shtml">Recent Reports & Talks</a></li>
	<li><a href="#">Link 1</a></li>
	<li><a href="#">Link 2</a></li>
	<li><a href="#">Link 3</a></li>
</ul>

<!-- Create Menu Settings: (Menu ID, Is Vertical, Show Timer, Hide Timer, On Click (options: 'all' * 'all-always-open' * 'main' * 'lev2'), Right to Left, Horizontal Subs, Flush Left, Flush Top) -->
<script type="text/javascript">qm_create(1,true,0,500,false,false,false,false,false);</script>

<!-- End Left Navigation Menu -->

